//! Safe RAII wrapper for HCCL collective communication.
//!
//! Provides `HcclCommunicator` for multi-device collective operations
//! (AllReduce, Send, Recv, AllGather, Broadcast) used by tensor parallelism
//! and pipeline parallelism.

use crate::error::{AscendError, Result};
use crate::memory::DeviceBuffer;
use crate::stream::Stream;
use hccl_sys::{
    HcclAllGather, HcclAllReduce, HcclBroadcast, HcclComm, HcclCommDestroy, HcclCommInitRootInfo,
    HcclDataType, HcclGetRootInfo, HcclRecv, HcclReduceOp, HcclReduceScatter, HcclResult,
    HcclRootInfo, HcclSend,
};

/// Check an HCCL return code, converting non-success to an error.
#[inline]
fn check_hccl(result: HcclResult) -> Result<()> {
    if result.is_ok() {
        Ok(())
    } else {
        Err(AscendError::InvalidArgument(format!(
            "HCCL error: {:?}",
            result
        )))
    }
}

// ─── Root Info ─────────────────────────────────────────────────────────

/// Generate a unique root info for communicator initialization.
///
/// Must be called by rank 0. The returned `HcclRootInfo` must be shared
/// with all other ranks (e.g., via a shared file or TCP).
pub fn get_root_info() -> Result<HcclRootInfo> {
    let mut root_info = HcclRootInfo::default();
    check_hccl(unsafe { HcclGetRootInfo(&mut root_info) })?;
    Ok(root_info)
}

/// Write root info to a file for inter-process sharing.
pub fn write_root_info_to_file(
    root_info: &HcclRootInfo,
    path: &std::path::Path,
) -> std::io::Result<()> {
    std::fs::write(path, &root_info.internal)
}

/// Read root info from a file written by rank 0.
pub fn read_root_info_from_file(path: &std::path::Path) -> std::io::Result<HcclRootInfo> {
    let bytes = std::fs::read(path)?;
    if bytes.len() != hccl_sys::HCCL_ROOT_INFO_BYTES {
        return Err(std::io::Error::new(
            std::io::ErrorKind::InvalidData,
            format!(
                "HcclRootInfo file has {} bytes, expected {}",
                bytes.len(),
                hccl_sys::HCCL_ROOT_INFO_BYTES
            ),
        ));
    }
    let mut root_info = HcclRootInfo::default();
    root_info.internal.copy_from_slice(&bytes);
    Ok(root_info)
}

// ─── Communicator ──────────────────────────────────────────────────────

/// RAII-safe HCCL communicator.
///
/// Wraps an `HcclComm` handle and destroys it on drop.
/// Each communicator represents this process's membership in a collective
/// communication group.
pub struct HcclCommunicator {
    comm: HcclComm,
    rank: u32,
    n_ranks: u32,
}

impl HcclCommunicator {
    /// Initialize a communicator for a specific rank.
    ///
    /// All ranks in the group must call this collectively. This call blocks
    /// until all ranks have joined.
    ///
    /// # Arguments
    /// - `n_ranks`: Total number of ranks in this group.
    /// - `root_info`: Root info generated by rank 0 via `get_root_info()`.
    /// - `rank`: This process's rank (0..n_ranks-1).
    pub fn init_rank(n_ranks: u32, root_info: &HcclRootInfo, rank: u32) -> Result<Self> {
        let mut comm: HcclComm = std::ptr::null_mut();
        check_hccl(unsafe {
            HcclCommInitRootInfo(n_ranks, root_info as *const _, rank, &mut comm)
        })?;
        Ok(Self {
            comm,
            rank,
            n_ranks,
        })
    }

    /// This rank's index within the communicator.
    pub fn rank(&self) -> u32 {
        self.rank
    }

    /// Total number of ranks in this communicator.
    pub fn n_ranks(&self) -> u32 {
        self.n_ranks
    }

    /// All-reduce sum (in-place): reduces across all ranks, result on all ranks.
    ///
    /// The buffer is used as both send and receive (in-place operation).
    ///
    /// # Arguments
    /// - `stream`: AscendCL stream for async execution.
    /// - `buf`: Device buffer to reduce in-place.
    /// - `count`: Number of elements (not bytes).
    /// - `dtype`: Element data type.
    pub fn all_reduce_sum(
        &self,
        stream: ascendcl_sys::AclrtStream,
        buf: &DeviceBuffer,
        count: u64,
        dtype: HcclDataType,
    ) -> Result<()> {
        let ptr = buf.ptr();
        check_hccl(unsafe {
            HcclAllReduce(
                ptr,
                ptr as *mut _,
                count,
                dtype,
                HcclReduceOp::Sum,
                self.comm,
                stream,
            )
        })
    }

    /// All-reduce with explicit send and receive buffers.
    pub fn all_reduce(
        &self,
        stream: ascendcl_sys::AclrtStream,
        send_buf: &DeviceBuffer,
        recv_buf: &DeviceBuffer,
        count: u64,
        dtype: HcclDataType,
        op: HcclReduceOp,
    ) -> Result<()> {
        check_hccl(unsafe {
            HcclAllReduce(
                send_buf.ptr(),
                recv_buf.ptr(),
                count,
                dtype,
                op,
                self.comm,
                stream,
            )
        })
    }

    /// All-gather: gather data from all ranks.
    ///
    /// Each rank contributes `send_count` elements. The output holds
    /// `send_count * n_ranks` elements.
    pub fn all_gather(
        &self,
        stream: ascendcl_sys::AclrtStream,
        send_buf: &DeviceBuffer,
        recv_buf: &DeviceBuffer,
        send_count: u64,
        dtype: HcclDataType,
    ) -> Result<()> {
        check_hccl(unsafe {
            HcclAllGather(
                send_buf.ptr(),
                recv_buf.ptr(),
                send_count,
                dtype,
                self.comm,
                stream,
            )
        })
    }

    /// Broadcast data from root rank to all ranks.
    pub fn broadcast(
        &self,
        stream: ascendcl_sys::AclrtStream,
        buf: &DeviceBuffer,
        count: u64,
        dtype: HcclDataType,
        root: u32,
    ) -> Result<()> {
        check_hccl(unsafe {
            HcclBroadcast(
                buf.ptr(),
                count,
                dtype,
                root,
                self.comm,
                stream,
            )
        })
    }

    /// Reduce-scatter: reduce across ranks and scatter result.
    pub fn reduce_scatter(
        &self,
        stream: ascendcl_sys::AclrtStream,
        send_buf: &DeviceBuffer,
        recv_buf: &DeviceBuffer,
        recv_count: u64,
        dtype: HcclDataType,
        op: HcclReduceOp,
    ) -> Result<()> {
        check_hccl(unsafe {
            HcclReduceScatter(
                send_buf.ptr(),
                recv_buf.ptr(),
                recv_count,
                dtype,
                op,
                self.comm,
                stream,
            )
        })
    }

    /// Point-to-point send to a specific rank.
    ///
    /// Must be paired with a corresponding `recv()` on the destination rank.
    pub fn send(
        &self,
        stream: ascendcl_sys::AclrtStream,
        buf: &DeviceBuffer,
        count: u64,
        dtype: HcclDataType,
        dest_rank: u32,
    ) -> Result<()> {
        check_hccl(unsafe {
            HcclSend(
                buf.ptr(),
                count,
                dtype,
                dest_rank,
                self.comm,
                stream,
            )
        })
    }

    /// Point-to-point receive from a specific rank.
    ///
    /// Must be paired with a corresponding `send()` on the source rank.
    pub fn recv(
        &self,
        stream: ascendcl_sys::AclrtStream,
        buf: &DeviceBuffer,
        count: u64,
        dtype: HcclDataType,
        src_rank: u32,
    ) -> Result<()> {
        check_hccl(unsafe {
            HcclRecv(
                buf.ptr(),
                count,
                dtype,
                src_rank,
                self.comm,
                stream,
            )
        })
    }
}

impl Drop for HcclCommunicator {
    fn drop(&mut self) {
        if !self.comm.is_null() {
            unsafe {
                let _ = HcclCommDestroy(self.comm);
            }
        }
    }
}

// Safety: HCCL communicators can be sent between threads.
// The HCCL runtime handles internal synchronization.
unsafe impl Send for HcclCommunicator {}
unsafe impl Sync for HcclCommunicator {}
