//! `hccl-sys` — Raw FFI bindings to HCCL (Huawei Collective Communication Library).
//!
//! Provides unsafe `extern "C"` declarations for `libhccl.so` functions.
//!
//! # Modules
//! - [`types`] — Enums, constants, and opaque handle types
//!
//! # Safety
//! All functions are `unsafe extern "C"`. Callers must ensure:
//! - AscendCL is initialized before calling HCCL functions
//! - Device context is set for the correct NPU device
//! - Buffers are valid device memory with correct sizes
//!
//! # Feature Flags
//! - `stub`: Skip linking `libhccl.so` (for development without CANN SDK)

pub mod types;

pub use types::*;

use std::os::raw::c_void;

// Re-export the stream type from ascendcl-sys for convenience
// HCCL operations take an aclrtStream parameter.
pub type AclrtStream = *mut c_void;

// ─── HCCL API Functions ────────────────────────────────────────────────

extern "C" {
    /// Generate a unique root info for communicator initialization.
    /// Must be called by rank 0, then broadcast to all other ranks.
    ///
    /// # Parameters
    /// - `root_info`: Output — filled with unique communication ID.
    ///
    /// # Returns
    /// `HcclResult::Success` on success.
    pub fn HcclGetRootInfo(root_info: *mut HcclRootInfo) -> HcclResult;

    /// Initialize a communicator for a specific rank.
    ///
    /// All ranks in the group must call this collectively with the same
    /// `root_info` and `n_ranks`. This call blocks until all ranks have joined.
    ///
    /// # Parameters
    /// - `comm`: Output — initialized communicator handle.
    /// - `n_ranks`: Total number of ranks in this group.
    /// - `root_info`: The root info generated by rank 0 via `HcclGetRootInfo`.
    /// - `rank`: This process's rank within the group (0..n_ranks-1).
    ///
    /// # Returns
    /// `HcclResult::Success` on success.
    pub fn HcclCommInitRootInfo(
        n_ranks: u32,
        root_info: *const HcclRootInfo,
        rank: u32,
        comm: *mut HcclComm,
    ) -> HcclResult;

    /// All-reduce: reduce tensor across all ranks, result available on all ranks.
    ///
    /// Supports in-place operation (`send_buf == recv_buf`).
    ///
    /// # Parameters
    /// - `send_buf`: Input device buffer.
    /// - `recv_buf`: Output device buffer (can be same as `send_buf`).
    /// - `count`: Number of elements (not bytes).
    /// - `data_type`: Element data type.
    /// - `op`: Reduction operation (Sum, Prod, Max, Min).
    /// - `comm`: Communicator handle.
    /// - `stream`: AscendCL stream for async execution.
    ///
    /// # Returns
    /// `HcclResult::Success` on success.
    pub fn HcclAllReduce(
        send_buf: *const c_void,
        recv_buf: *mut c_void,
        count: u64,
        data_type: HcclDataType,
        op: HcclReduceOp,
        comm: HcclComm,
        stream: AclrtStream,
    ) -> HcclResult;

    /// All-gather: gather data from all ranks, result concatenated on all ranks.
    ///
    /// Each rank contributes `send_count` elements. The output buffer holds
    /// `send_count * n_ranks` elements.
    ///
    /// # Parameters
    /// - `send_buf`: Input device buffer (this rank's contribution).
    /// - `recv_buf`: Output device buffer (holds all ranks' data).
    /// - `send_count`: Number of elements this rank sends.
    /// - `data_type`: Element data type.
    /// - `comm`: Communicator handle.
    /// - `stream`: AscendCL stream for async execution.
    pub fn HcclAllGather(
        send_buf: *const c_void,
        recv_buf: *mut c_void,
        send_count: u64,
        data_type: HcclDataType,
        comm: HcclComm,
        stream: AclrtStream,
    ) -> HcclResult;

    /// Broadcast: broadcast data from root rank to all ranks.
    ///
    /// # Parameters
    /// - `buf`: Device buffer (input on root, output on others).
    /// - `count`: Number of elements.
    /// - `data_type`: Element data type.
    /// - `root`: Root rank that provides the data.
    /// - `comm`: Communicator handle.
    /// - `stream`: AscendCL stream.
    pub fn HcclBroadcast(
        buf: *mut c_void,
        count: u64,
        data_type: HcclDataType,
        root: u32,
        comm: HcclComm,
        stream: AclrtStream,
    ) -> HcclResult;

    /// Reduce-scatter: reduce across ranks and scatter result.
    ///
    /// # Parameters
    /// - `send_buf`: Input device buffer (full size).
    /// - `recv_buf`: Output device buffer (1/n_ranks of full size).
    /// - `recv_count`: Number of elements this rank receives.
    /// - `data_type`: Element data type.
    /// - `op`: Reduction operation.
    /// - `comm`: Communicator handle.
    /// - `stream`: AscendCL stream.
    pub fn HcclReduceScatter(
        send_buf: *const c_void,
        recv_buf: *mut c_void,
        recv_count: u64,
        data_type: HcclDataType,
        op: HcclReduceOp,
        comm: HcclComm,
        stream: AclrtStream,
    ) -> HcclResult;

    /// Point-to-point send to a specific rank.
    ///
    /// Must be paired with a corresponding `HcclRecv` on the destination rank.
    ///
    /// # Parameters
    /// - `send_buf`: Input device buffer.
    /// - `count`: Number of elements.
    /// - `data_type`: Element data type.
    /// - `dest_rank`: Destination rank within the communicator.
    /// - `comm`: Communicator handle.
    /// - `stream`: AscendCL stream.
    pub fn HcclSend(
        send_buf: *const c_void,
        count: u64,
        data_type: HcclDataType,
        dest_rank: u32,
        comm: HcclComm,
        stream: AclrtStream,
    ) -> HcclResult;

    /// Point-to-point receive from a specific rank.
    ///
    /// Must be paired with a corresponding `HcclSend` on the source rank.
    ///
    /// # Parameters
    /// - `recv_buf`: Output device buffer.
    /// - `count`: Number of elements.
    /// - `data_type`: Element data type.
    /// - `src_rank`: Source rank within the communicator.
    /// - `comm`: Communicator handle.
    /// - `stream`: AscendCL stream.
    pub fn HcclRecv(
        recv_buf: *mut c_void,
        count: u64,
        data_type: HcclDataType,
        src_rank: u32,
        comm: HcclComm,
        stream: AclrtStream,
    ) -> HcclResult;

    /// Destroy a communicator and release its resources.
    ///
    /// # Parameters
    /// - `comm`: Communicator handle to destroy.
    pub fn HcclCommDestroy(comm: HcclComm) -> HcclResult;
}
